### ISSUE TITLE
add branch specific preview environment variables

### ISSUE THREAD

**Issue by ijin** [HiDeoo/vercel-env-push#15]
### Is your feature request related to a problem?

Currently I can only add production, preview & development env vars. I would like to add branch specific variables as described here.

https://vercel.com/docs/concepts/projects/environment-variables#preview-environment-variables

The Vercel CLI can do this with `vercel env add API_KEY preview staging`

### Describe the solution you'd like

`vercel-env-push .env.staging preview staging`

**Comment by HiDeoo** [comment]
Thanks for your suggestion.

I just released [`v0.3.0`](https://github.com/HiDeoo/vercel-env-push/releases/tag/v0.3.0) which adds support for targeting a specific Git branch when pushing environment variables to the Preview environment.

The branch can be specified from the CLI using the `-b` or `--branch` option and from the API with the `branch` option.
