### ISSUE TITLE
Pushing many env vars fails because requests exceed Vercel's API throttling

### ISSUE THREAD

**Issue by canadaduane** [HiDeoo/vercel-env-push#22]
### Describe the bug

About 21 environment variables succeeded, but the 22nd failed. I have 58 environment variables in total:

```
✖ Pushing environment variables
Something went wrong: Unable to remove environment variable 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY' from 'development'.
Error: Command failed: npx --yes vercel env rm NEXT_PUBLIC_STRIPE_PUBLIC_KEY development -y
Vercel CLI 23.1.2
Error! Too many requests - try again in -478 ms (more than 120, code: "api-projects").

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npx --yes vercel env rm NEXT_PUBLIC_STRIPE_PUBLIC_KEY development -y',
  stdout: '',
  stderr: 'Vercel CLI 23.1.2\n' +
    'Error! Too many requests - try again in -478 ms (more than 120, code: "api-projects").\n'
}
````

### To Reproduce

With a large set of environment variables, push to vercel.

### Expected behavior

It would be nice if an automatic back-off came into play here, retrying after a timeout when reaching this API limit. Another option might be to add a configurable delay between requests?

### How often does this bug happen?

Every time

### System Info

Mac OS 13.2.1 / M2

**Comment by HiDeoo** [comment]
Interesting, there is a rate limiter right now in place that limit to 8 API calls per 10 seconds but I assume this is not enough / there are others limitations. As soon as I have the time, I'll investigate if I can get a more reliable way to get these limitations or if they are documented. I'll also setup a repro and figure out the "best" solution to handle these cases.

Thanks for your report.

**Comment by canadaduane** [comment]
I set it to 4 per 10 seconds and this was a good workaround for now. Thanks.

**Comment by HiDeoo** [comment]
In the next version, the rate limit will be 6 requests per 10 seconds instead of 8.

I tested this limit with 100 environments variables pushed to 2 environments and it did not fail. If I get new reports regarding this issue after the change is published, I'll make the limit configurable as it's mostly impacting people having a lot of environment variables.
