### ISSUE TITLE
Production env vars can be unlinked by changing development env vars

### ISSUE THREAD

**Issue by canadaduane** [HiDeoo/vercel-env-push#23]
### Describe the bug

We have several vercel env vars that are "linked" together in that they have the same key, but are available to multiple environments--Production, Preview, and Development in our case. I attempted to updated all Development vars using `vercel-env-push`, but our production system lost its environment variables--the ones that had been linked across environments were now all set to Development environment only. Luckily, this didn't cause any down time for us, but it did prevent us from being able to push new releases. We manually had to go back in to identify which variables had been linked in Production and put them back the way they were.

### To Reproduce

1. In Vercel tag a variable as belonging to more than one environment, e.g. Production, Development
2. Use `vercel-env-push` to update a Development variable
3. Note that the Production tag is now missing from that variable.

### Expected behavior

Updating Development env vars should not affect other environments.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Sorry to hear that.

After a bit of investigations, this is a consequence of what I would consider multiple weird behaviors on the Vercel side:

- The Vercel CLI does not provide a command to update an environment variable. There is [only](https://vercel.com/docs/cli/env) a `vercel env rm` and a `vercel env add`. One could think that adding an existing variable would override it but this is not the case as you would get the `"Another Environment Variable with the same Name and Environment exists in your project"` error. So basically, to update a variable using the Vercel CLI, you have first to remove it and add it again which is what `vercel-env-push` is doing under the hood.
- When creating an environment variable for multiple environments, `vercel-env-push` will actually create 2 environment variables with the same name, each one associated with a different environment. This means that we can safely update or remove the variable from one environment without affecting the other one. However, if you already have a previously existing variable which is associated with multiple environments (e.g. added through the website and selecting multiple environments for a variable), explicitly asking to remove this variable __from a specific environment__ using the Vercel CLI will actually remove it from all environments.

I will add a warning in the README to highlight this behavior as I think this is the only thing I can do at the moment with theses limitations.
